### ISSUE TITLE
Show total result size instead of 500+ in full text search page 

### ISSUE THREAD

**Issue by vogelino** [berlin/haushaltsdaten#70]
![image](https://user-images.githubusercontent.com/2759340/190355028-488966b1-48ce-4464-83e4-2d9d6caad11b.png)

**Comment by vogelino** [comment]
1. Make a head call to the API to get the total count
2. render it to the right place

**Questions:**
The call is a remote procedure call. The RPC should return the total count of rows.

**Comment by ff6347** [comment]
Example request done with Deno:

```ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@1.35.3";

const supabase = createClient(
	"<SUPABASE URL>",
	"<ANON TOKEN>",
);

const { data, error, count } = await supabase.rpc(
	"ftc",
	{ search: "mitte" },
	{ count: "exact" },
);

if (error) {
	console.error(error);
	throw error;
}
console.log(count);

```

We make the request [here](https://github.com/berlin/haushaltsdaten/blob/6b61cf078cc10aa0c66e672815fb7e8e93445647/pages/search.tsx#L74)
