### ISSUE TITLE
Improve spinner on full text search

### ISSUE THREAD

**Issue by ff6347** [berlin/haushaltsdaten#72]
The placement of the spinner on the full text search could get some love

**Comment by vogelino** [comment]
Idee: Loading skeleton for better expectation management. 
Right now: Loading spinner is badly placed

**Comment by vogelino** [comment]
Qucik fix: Better CSS padding and centering
Long Fix: Loading Skeleton Component

**Comment by julizet** [comment]
PR can be found here: https://github.com/berlin/haushaltsdaten/pull/96
